//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avitos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> MerchId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    
        public virtual Merch Merch { get; set; }
        public virtual User User { get; set; }
    }
}
